services:

  nuxt:
    image: ghcr.io/kevindebenedetti/api-lab:latest
    pull_policy: always
    restart: always
    expose:
      - 3000
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-lab.rule=Host(`api-lab.kevindb.dev`)
      - traefik.http.routers.api-lab.entrypoints=websecure
      - traefik.http.services.api-lab.loadbalancer.server.port=3000

networks:
  dokploy-network:
    external: true