name: Deploy API Lab

on:
    push:
      branches:
        - main

jobs:
    ghcr:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
            attestations: write
            id-token: write

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push App Docker image
          run: |
            docker build \
            --build-arg NUXT_API_ENTREPRISES_GOUV="${{ secrets.NUXT_API_ENTREPRISES_GOUV }}" \
            -t ghcr.io/${{ vars.repository_owner }}/api-lab:latest ./
            docker push ghcr.io/${{ vars.repository_owner }}/api-lab:latest

        - name: Logout from GHCR
          run: docker logout ghcr.io

    deploy:
      needs: [ghcr]
      runs-on: ubuntu-latest
      steps:
        - name: Deploy using ssh
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}   
            key: ${{ secrets.SSH_KEY }}
            port: ${{ secrets.SSH_PORT }}
            script: |
              docker stack rm api-lab_stack
              cd api-lab/
              docker pull ghcr.io/${{ vars.repository_owner }}/api-lab:latest

              docker stack deploy -c compose.prod.yaml api-lab_stack

              docker container prune -f
              docker image prune -f
              
              docker logout ghcr.io    